# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cb261430b817b29ec95b75e95e637a1e563ab85981572dc78fe13e8a04016a25ce1ebcfec2bcdaea206e8def63beb8e9a5335b2a56f203319a8028ceaa273eb

test:
  secret_key_base: 47d0abb515d32f47f1fc7abae255962b243405172ba879429f8073c0193cfd41d010c5931766fd232a7a4ea4f6c1ae6c6cf5d79a2718e85d552801bda27bc491

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
